# Site settings
title: Ryan Adlam
description: Ryan Adlam
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Adlam
user_description: Data Scientist with 5+ years of experience and a Master’s in Mathematics./n Passionate about applying Causal Inference, Machine Learning, and Advanced Statistical techniques to solve complex problems and drive impactful decision-making.
user_title: Data Scientist
email: ryan-adlam@outlook.com
github_username: ryanadlam

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
